# Generated by Django 5.0 on 2023-12-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='voted',
            field=models.IntegerField(default=0),
        ),
    ]
